apiVersion: v1
kind: Pod
metadata:
  labels:
    acme.com/lifespan-requested: "3"
  name: lifespan-three
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: lifespan-three
  restartPolicy: Always
