apiVersion: v1
kind: Pod
metadata:
  name: no-labels
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: no-labels
  restartPolicy: Always
