apiVersion: v1
kind: Config
clusters:
  - name: my-authn-service
    cluster:
      # for cloud run
      server: https://webhook-server-995081019036.us-central1.run.app/authenticate
      # for self hosted`
      # certificate-authority: /var/lib/minikube/certs/webhook_ca.crt
      # server: https://webhook.esodemoapp2.com:8081/authenticate
users:
  - name: my-api-server
    user:
      token: test-token
      # client-certificate: /var/lib/minikube/certs/webhook_plugin.crt
      # client-key: /var/lib/minikube/certs/webhook_plugin.key
current-context: webhook
contexts:
- context:
    cluster: my-authn-service
    user: my-api-sever
  name: webhook